### ISSUE TITLE
[feat] GPT API를 호출하여 페르소나를 적용한 일기 생성

### ISSUE THREAD

**Issue by minji1289** [ewha-cse-HACK/HACK_Server#87]
### Description
그림일기 기능을 위해, GPT API가 페르소나를 반영한 일기 텍스트를 생성하고 DB에 이를 저장함

### Todo
- [x]  GPT API에게 일기 생성 프롬프트 명령 전달
> - [x]  페르소나를 반영하여 일기를 생성하게끔 프롬프트 엔지니어링하는 작업
- [x]  일기 엔티티 생성
- [x] GPT가 생성한 일기 텍스트 DB에 저장

**Comment by minji1289** [comment]
### GPT가 "페르소나"를 반영한 일기 생성
[feat] GPT: 일기 생성 -> GPT: 일기 1문장 요약 -> Papago: KO to EN -> DALL-E: 이미지 생성:
bc6b5f9cfc4df1d8707af7fbdb9007e147909173

### 생성한 일기를 DB에 저장하는 로직 
[feat] GPT가 생성한 일기 DB에 저장: bab2d1edab7c2f13e8fe1eed30d06eced901173e
