### ISSUE TITLE
[feat] base64 json을 MultipartFile로 변환하여 S3에 업로드

### ISSUE THREAD

**Issue by minji1289** [ewha-cse-HACK/HACK_Server#88]
## DALL-E 그림일기 이미지 생성 로직
1️⃣ DALL-E API는 **GPT가 생성한 `페르소나`가 반영된 일기**를 프롬프트(Prompt)로 전달받아 이미지를 생성한다. 
이 때, DALL-E API 호출시 Response의 Format을 **base64** Json String으로 설정한다. 

> 만약 DALL-E가 이미지를 생성하고 url의 형식으로 응답을 보낸다면, 해당 url로 접근하여 그 이미지 파일을 S3 버킷에 업로드를 해야한다. 이 경우, DALL-E가 보낸 응답 url로 접근하여 이미지 파일을 객체로 받아 이를 버킷에 업로드하는 과정이 필요하게 된다. 이를 ❗단 한 번의 API 호출로❗ 구현하는 것은 클라이언트의 처리 과정 없이는 어렵다고 판단하였기에, 💡DALL-E API 호출에 대한 응답을 **base64** Json String으로 받아 MultipartFile의 형태로 S3 버킷에 이미지를 업로드하는 로직💡을 고안하게 되었다.

따라서, S3에 그림일기 이미지를 업로드하기 위해 다음과 같은 과정을 거친다:
2️⃣ DALL-E API를 호출한 응답값인 base64 Json String을 **byte [](byte array)로 변환**한다.
3️⃣ byte []로 변환된 그림일기 이미지를 MultipartFile로 변환한다.
4️⃣ MultiPartFile로 변환된 그림일기 이미지를 S3 버킷에 업로드한다.

## Task
- [x] DALL-E API 호출시 Response Format을 base64-encoded JSON으로 변경: .responseFormat("b64_json")
참고: https://velog.io/@minji1289/Springboot-%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8%EB%A1%9C-DALL-E-API-%ED%98%B8%EC%B6%9C%ED%95%98%EA%B8%B0

- [x] base64 Json String -> byte []
➡️ `Base64.decodeBase64()` 이용!

### ImageGeneratorController.java
        import org.apache.commons.codec.binary.Base64;

        public class ImageGeneratorController {
                // (...생략)
        String img = aiService.generatePicture(naverTransService.getTransSentence(shortKoJour)); // papago를 거쳐 DALL-E를 통해 반환된 b64_json String
        byte[] image = Base64.decodeBase64(img); //b64 string -> byte[]
                // (...생략)
        }

- [x] byte[] -> MultipartFile

        import com.hack.hack_server.Global.S3.S3Uploader;        
        import org.springframework.web.multipart.MultipartFile;
        import org.springframework.mock.web.MockMultipartFile;
        import java.io.ByteArrayInputStream;
        import java.io.ByteArrayOutputStream;
        import java.io.IOException;

        public class ImageGeneratorController {
                private final S3Uploader s3Uploader;

                // (...생략)
                int totalCnt = 1024;
                try (ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream(totalCnt)) {
                    int offset = 0;
                    while (offset < image.length) {
                        int chunkSize = Math.min(totalCnt, image.length - offset);

                        byte[] byteArray = new byte[chunkSize];
                        System.arraycopy(image, offset, byteArray, 0, chunkSize);

                        byteArrayOutputStream.write(byteArray);
                        byteArrayOutputStream.flush();

                        offset += chunkSize;
                    }

                    // Convert the ByteArrayOutputStream to ByteArrayInputStream
                    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(byteArrayOutputStream.toByteArray());

                    // Create an MultipartFile object
                    MultipartFile multipartFile = new MockMultipartFile("그림 일기", byteArrayInputStream.readAllBytes());

                    s3Uploader.saveFile(multipartFile); //s3에 멀티파트 파일로 직접 업로드
                    } catch (IOException e) {
                }
        // (...생략)
        }

➡️ 이때 호출된 S3Uploader.java 속 saveFile()는 MultipartFile을 S3 버킷에 업로드하는 기능을 하는 함수이다.

- [x] MultipartFile을 S3 버킷에 업로드 하는 코드
- 그림일기 이미지 저장용 폴더를 따로 생성하여, 해당 폴더에 이미지를 업로드하였다.
### S3Uploader.java

        import com.amazonaws.services.s3.model.ObjectMetadata;
        import org.springframework.web.multipart.MultipartFile;

        public class S3Uploader {
                public String saveFile(MultipartFile multipartFile) throws IOException {
                        String originalFilename = multipartFile.getName();

                        ObjectMetadata metadata = new ObjectMetadata();
                        metadata.setContentLength(multipartFile.getSize());
                        metadata.setContentType(multipartFile.getContentType());

                        amazonS3Client.putObject(bucket + "/그림일기", multipartFile.getName(), multipartFile.getInputStream(), metadata);
                        return amazonS3Client.getUrl(bucket + "/그림일기", originalFilename).toString();
                }
        }

**Comment by minji1289** [comment]
[feat] Journal 엔티티에 그림일기 저장 후 s3 업로드 - 1차 구현 : 51cc168
[feat] Journal 엔티티에 그림일기 저장 후 MultipartFile 형태로 s3에 업로드: ff1d023


[fix] S3 버킷 폴더 경로 추가 & 그림일기 댓글이 없을 경우 api 예외처리: e36288f
- 업로드시 '그림일기' 폴더 안에 업로드 되도록 폴더 경로 설정 -> 이미지 url 조회시에도 바뀐 경로로 조회

**Comment by minji1289** [comment]
구현 내용에 대해 작성한 velog 포스트: https://velog.io/@minji1289/DALL-E-API-%ED%98%B8%EC%B6%9C-%ED%9B%84-base64-json%EC%9D%84-MultipartFile%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%98%EC%97%AC-AWS-S3%EC%97%90-%EC%97%85%EB%A1%9C%EB%93%9C#4%EF%B8%8F%E2%83%A3-multipartfile%EB%A1%9C-%EB%B3%80%ED%99%98%EB%90%9C-%EC%9D%B4%EB%AF%B8%EC%A7%80%EB%A5%BC-s3-%EB%B2%84%ED%82%B7%EC%97%90-%EC%97%85%EB%A1%9C%EB%93%9C%ED%95%9C%EB%8B%A4
